AWSTemplateFormatVersion: 2010-09-09
  
Parameters:
  ExecutionRoleArn:
    Type: String
  ModelDataUrl:
    Type: String
  Image:
    Type: String
  InstanceType:
    Type: String
  InitialInstanceCount:
    Type: String
  Project:
    Type: String

Resources:

  Model:
    Type: AWS::SageMaker::Model
    Properties:
      ExecutionRoleArn:
        Ref: ExecutionRoleArn
      PrimaryContainer:
        Image:
          Ref: Image
        Mode: "SingleModel"
        ModelDataUrl: 
          Ref: ModelDataUrl

  EndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants: # Required
        - InitialInstanceCount:
            Ref: InitialInstanceCount
          InstanceType:
            Ref: InstanceType
          ModelName: 
            Fn::GetAtt: Model.ModelName
          VariantName:
            Ref: Project
          InitialVariantWeight: 1

  Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName