version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - cd train
      - pip3 install -r reqs.txt
      - chmod +x train.py
      - python3 train.py
artifacts:
  files:
    - '**/*'